# Generated by Django 3.0.2 on 2020-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='fichier')),
            ],
        ),
    ]
