# Generated by Django 3.0.2 on 2020-03-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMO', '0003_delete_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='nom',
            new_name='name',
        ),
    ]
