# Generated by Django 3.0.2 on 2020-03-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMO', '0004_auto_20200317_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='name',
            new_name='nom',
        ),
    ]
