# Generated by Django 3.0.2 on 2020-03-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMO', '0005_auto_20200317_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrateur',
            new_name='Essai',
        ),
    ]
