# Generated by Django 3.0.2 on 2020-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMO', '0006_auto_20200320_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essai',
            old_name='mail',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='essai',
            old_name='mdp',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='essai',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='essai',
            name='prenom',
        ),
        migrations.AddField(
            model_name='essai',
            name='contenu',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
